#!/bin/bash
usage(){
	echo "Usage: $0 <keystore_filename> <keystore_password> <key_name> [<key_password>]"
	exit 1
}

[[ $# -lt 3 ]] && usage

WORKSPACE=${WORKSPACE:-$( cd $(dirname $0)/../../.. ; pwd -P )}

SIGN_STORE=$1
SIGN_STOREPASS=$2
SIGN_KEY=$3
SIGN_KEYPASS=$4 

echo "Signing..."
jarsigner -sigalg MD5withRSA -digestalg SHA1 -keystore $SIGN_STORE -storepass $SIGN_STOREPASS $SIGN_KEYPASS_OPT $WORKSPACE/app/build/outputs/apk/app-release-unsigned.apk $SIGN_KEY
$ZIPALIGN_JENKINS -f 4 $WORKSPACE/app/build/outputs/apk/app-release-unsigned.apk $WORKSPACE/kore-release.apk
echo "$WORKSPACE/kore-release.apk created"
